### ISSUE TITLE
Cake.Recipe 2.0.0 Release Roadmap

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#396]
- [x] Abstraction of build servers https://github.com/cake-contrib/Cake.Recipe/issues/259
- [x] Run on .Net Core https://github.com/cake-contrib/Cake.Recipe/issues/152
- [x] Run MSBuild on Unix platforms when possible, with fallback to XBuild
- [x] Update all tools to latest version - Being handled by Cake.AddinDiscoverer
- [x] Move GitVersion out of Setup, into own task, so it can be overridden https://github.com/cake-contrib/Cake.Recipe/issues/217
- [x] Change defaults for parameters and tools
- [x] Update to Cake Version 0.33.0 https://github.com/cake-contrib/Cake.Recipe/pull/442
- [x] Make tool/addin versions configurable https://github.com/cake-contrib/Cake.Recipe/issues/214
- [x] Don't delete nupkg files at the end of build - due to the fact that Bakery doesn't like this https://github.com/cake-contrib/Cake.Recipe/issues/448
- [x] Remove mention of MyGet from everywhere.  Don't think we should couple directly to MyGet, instead name this as AlternativeNugetSource or something similar, which could then be MyGet if required https://github.com/cake-contrib/Cake.Recipe/issues/447
- [x] Remove usage of GitLink.  Going forward, we should look to make use of SourceLink, or the built in tooling that now exists. https://github.com/cake-contrib/Cake.Recipe/issues/446
- [x] Remove Cake.Graph https://github.com/cake-contrib/Cake.Recipe/issues/359

**Comment by gep13** [comment]
@AdmiringWorm @wwwlicious @Jericho @pascalberger here is a top level overview of important things I think we need to handle in the next release of Cake.Recipe.  Some of these, and others, are already included as [issues](https://github.com/cake-contrib/Cake.Recipe/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0) on the next milestone, but I wanted to capture the highlights here.

Have I missed anything else that we should be looking at in the next release?

**Comment by AdmiringWorm** [comment]
> @AdmiringWorm I didn't call it out in the above list, but it is in the milestone:
> 
> #356
> 
> 😄

I opened a PR to add this support now: #480

**Comment by gep13** [comment]
@AdmiringWorm I have been giving this one:

> Use BuildData class for all tasks

Some thought, and for now, I think we defer this to a later release.  Thoughts?

The way that Cake.Recipe is invoked just now, I am not clear exactly on how the call to `SetParameters` would work with a typed context.

**Comment by AdmiringWorm** [comment]
I got no objections with deferring the BuildData class to a later release

**Comment by gep13** [comment]
@AdmiringWorm all the tasks on this check list have been completed, so happy to say that we can close out this tracking issue, and start to get ready for a 2.0.0 release of Cake.Recipe.  Just some documentation items left to complete, but hoping to get to those over the next couple days.
